# -*- coding: utf-8 -*-
"""TraductorES-EN.ipynb

Automatically generated by Colab.

in the github repository, you can find the original notebook with the code and explanations:s
"""

import nltk
nltk.download('punkt')

!pip install --upgrade sympy sentencepiece sacremoses
from transformers import pipeline

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

def translate_with_transformers(text):
    model_name = "Helsinki-NLP/opus-mt-en-es" #change model for diferent translation direction
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

    inputs = tokenizer(text, return_tensors="pt", padding=True)

    translated_tokens = model.generate(**inputs)

    result = tokenizer.decode(translated_tokens[0], skip_special_tokens=True)
    return result

def translate(text, method="transformers"):
    if method == "transformers":
        return translate_with_transformers(text)
    else:
        return "Método de traducción no válido."

# Example text
text = """I had a great weekend. On Friday afternoon, I finished work at 5 PM.\nI went home and took a shower. Then I went to see a couple of my friends at a bar downtown."""
try:
    traduccion = translate(text, method="transformers")
    print("Traducción directa con Modelo:\n", traduccion)
except Exception as e:
    import traceback
    print(f"Error al ejecutar la traducción: {e}")
    traceback.print_exc()